### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by joshrowley** [joshrowley/vizcab.old#5]

**Comment by VizCab** [comment]
You got my new fav icon art right?
![viz_fav](https://cloud.githubusercontent.com/assets/2963673/11731102/e9513458-9f4d-11e5-8642-99071f0c19a2.png)

**Comment by joshrowley** [comment]
yeah i did i'll grab it from slack

**Comment by joshrowley** [comment]
hmm the airplane wifi doesn't let me download this from http://realfavicongenerator.net/

we should use a 260 x 260 master image to generate all the other icons using that site

**Comment by VizCab** [comment]
I emailed you a revised fav icon.
